# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nextjs-euro

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Yarn install, build
      run: |
        yarn
        yarn build
      # npm run test --if-present
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Copy Public & Static Folders
      run: |
        cp -r public .next/standalone
        cp -r ./.next/static .next/standalone

    - name: Zip artifact for deployment
      run: zip -r --symlinks .next/standalone 

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: release.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nextjs-euro'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ae5c28683f7424d86a9e75af794ed88 }}
        package: .